[meta]
name = "Arbitrary Record Loader"
author = "ar....."
version = "0.1.0"
category = ""

[script]
dependencies = [ "NadeoServices", "MLHook" ]
optional_dependencies = [ "ChampionMedals" ]
